name: PasswordWhitelist
version: 1.3
description: A password based server whitelist
author: gronnmann & Butterscotch
api-version: '1.21.5'

main: io.github.gronnmann.passwordwhitelist.PasswordWhitelist